import {
  FaLaptop,
  FaMobileAlt,
  FaGamepad,
  FaTv,
  FaCamera,
  FaNetworkWired,
  FaTools,
  FaBox,
  FaChargingStation,
  FaHouseUser,
  FaLock,
  FaBell,
  FaPumpSoap,
  FaBroom,
  FaFan,
  FaCogs
} from "react-icons/fa";
import { GiDisc } from "react-icons/gi";
import { MdDevicesOther, MdCable } from "react-icons/md";
import { SiPcgamingwiki } from "react-icons/si";

export const iconCategories = {
  "computer-components": SiPcgamingwiki,
  "computer-systems": FaLaptop,
  "laptops-tablets-and-accessories": FaLaptop,
  "monitors-and-displays": FaTv,
  "computer-peripherals": MdDevicesOther,
  "vr-virtual-reality": FaGamepad,
  "storage-devices-and-consumables": FaBox,
  "power-protection": FaChargingStation,
  "printers-scanners-and-consumables": FaTools,
  "network-equipment": FaNetworkWired,
  "electronics": FaCogs,
  "cables": MdCable,
  "tv-video-and-accessories": FaTv,
  "photo-and-video-accessories": FaCamera,
  "mobile-phones-and-accessories": FaMobileAlt,
  "gaming-peripheral-devices": FaGamepad,
  "navigation-systems-dashcam": FaCamera,
  "telescopes": FaCamera,
  "binoculars": FaCamera,
  "microscopes": FaCamera,
  "accessories-optics": FaCamera,
  "office-products": FaHouseUser,
  "software": GiDisc,
  "batteries-and-chargers": FaChargingStation,
  "household-products": FaHouseUser,
  "cable-locks": FaLock,
  "bells": FaBell,
  "bicycle-pumps": FaPumpSoap,
  "vacuum-cleaners": FaBroom,
  "air-purifiers": FaFan,
  "service": FaTools,
  "stem": FaCogs
};
