export const newProducts = [{
    id: 1,
    name: 'Лаптоп LENOVO IdeaPad 1 15IJL7 82LX00BBBM 16.6", INTEL CELERON N4500, RAM 4 GB, SSD 128 GB, INTEL UHD GRAPHICS, WINDOWS 11 HOME S, ABYSS BLUE',
    price: 519.0,
    discount: 20,
    image: "/products/laptop.jpg",
    code: 123456,
    stock: 44,
    utils: {
      type: "Laptop",
      ram: "4 GB",
      ssd: "128 GB",
      processor: "INTEL CELERON N4500",
      graphics: "INTEL UHD GRAPHICS",
      os: "WINDOWS 11 HOME S",
      color: "ABYSS BLUE",
      screen: '16.6"',
      resolution: "1920x1080",
      weight: "1.6 kg",
      dimensions: "329.4 x 212.9 x 16.6 mm",
      battery: "4-cell Li-ion, 50 Wh, 3.5 hours",
    },
  },
  {
    id: 2,
    name: "Лаптоп HP Pavilion 16-eg2086nm, INTEL CORE I5-1235U, RAM 16 GB, SSD 512 GB, INTEL IRIS XE, WINDOWS 11 HOME, SILVER",
    price: 1250.0,
    discount: 20,
    image: "/products/laptop2.jpg",
    code: 123457,
    stock: 30,
    utils: {
      type: "Laptop",
      ram: "16 GB",
      ssd: "512 GB",
      processor: "INTEL CORE I5-1235U",
      graphics: "INTEL IRIS XE",
      os: "WINDOWS 11 HOME",
      color: "SILVER",
      screen: '16.6"',
      resolution: "1920x1080",
      weight: "1.7 kg",
      dimensions: "358 x 235 x 18 mm",
      battery: "3-cell Li-ion, 41 Wh, 6 hours",
    },
  },
  {
    id: 3,
    name: "Desktop PC Lenovo ThinkCentre M90t, INTEL CORE I7-12700, RAM 16 GB, SSD 512 GB, NVIDIA GTX 1660 SUPER, WINDOWS 11 PRO",
    price: 1600.0,
    discount: 20,
    image: "/products/pc.jpg",
    code: 123458,
    stock: 20,
    utils: {
      type: "PC",
      ram: "16 GB",
      ssd: "512 GB",
      processor: "INTEL CORE I7-12700",
      graphics: "NVIDIA GTX 1660 SUPER",
      os: "WINDOWS 11 PRO",
      color: "BLACK",
      weight: "8.2 kg",
      dimensions: "175 x 430 x 450 mm",
    },
  },
  {
    id: 10,
    name: "Desktop PC HP Pavilion Gaming TG01-2170m, AMD RYZEN 5 5600G, RAM 16 GB, SSD 512 GB, NVIDIA RTX 3050, WINDOWS 11 HOME",
    price: 1350.0,
    discount: 20,
    image: "/products/pc2.jpg",
    code: 123459,
    stock: 16,
    utils: {
      type: "PC",
      ram: "16 GB",
      ssd: "512 GB",
      processor: "AMD RYZEN 5 5600G",
      graphics: "NVIDIA RTX 3050",
      os: "WINDOWS 11 HOME",
      color: "BLACK",
      weight: "7.8 kg",
      dimensions: "160 x 360 x 380 mm",
    },
  },
  {
    id: 11,
    name: 'Smartphone Samsung Galaxy S23, 8GB RAM, 256GB Storage, 6.1" AMOLED, ANDROID 13, PHANTOM PINK',
    price: 999.0,
    discount: 20,
    image: "/products/phone.jpg",
    code: 123460,
    stock: 50,
    utils: {
      type: "Phone",
      ram: "8 GB",
      storage: "256 GB",
      processor: "SNAPDRAGON 8 GEN 2",
      screen: '6.1" AMOLED',
      resolution: "2340x1080",
      os: "ANDROID 13",
      color: "PHANTOM PINK",
      weight: "168 g",
      battery: "3900 mAh",
    },
  },
  {
    id: 12,
    name: 'Smartphone Apple iPhone 14, 6GB RAM, 128GB Storage, 6.1" OLED, IOS 16, MIDNIGHT',
    price: 1199.0,
    discount: 20,
    image: "/products/phone2.jpg",
    code: 123461,
    stock: 40,
    utils: {
      type: "Phone",
      ram: "6 GB",
      storage: "128 GB",
      processor: "A15 BIONIC",
      screen: '6.1" OLED',
      resolution: "2532x1170",
      os: "IOS 16",
      color: "MIDNIGHT",
      weight: "172 g",
      battery: "3279 mAh",
    },
  },
  {
    id: 13,
    name: "Printer HP LaserJet Pro M404dw, MONO LASER, WIFI, USB, A4",
    price: 299.0,
    discount: 20,
    image: "/products/printer.jpg",
    code: 123462,
    stock: 25,
    utils: {
      type: "Printer",
      connectivity: "WIFI, USB",
      color: "BLACK",
      paperSize: "A4",
      weight: "8.5 kg",
      dimensions: "380 x 360 x 250 mm",
    },
  },
  {
    id: 14,
    name: 'Monitor Dell UltraSharp U2723QE 27", 4K UHD, IPS, HDMI/DP, BLACK',
    price: 499.0,
    discount: 20,
    image: "/products/monitor.jpg",
    code: 123463,
    stock: 18,
    utils: {
      type: "Monitor",
      screen: '27"',
      resolution: "3840x2160",
      panel: "IPS",
      connectivity: "HDMI, DP, USB-C",
      color: "BLACK",
      weight: "6.5 kg",
      dimensions: "613 x 366 x 54 mm",
    },
  },
  {
    id: 15,
    name: "Keyboard Logitech MX Keys, WIRELESS, BLUETOOTH, BLACK",
    price: 129.0,
    discount: 20,
    image: "/products/keyboard.jpg",
    code: 123464,
    stock: 60,
    utils: {
      type: "Keyboard",
      connectivity: "WIRELESS, BLUETOOTH",
      color: "BLACK",
      weight: "810 g",
      dimensions: "430 x 131 x 20 mm",
    },
  },
  {
    id: 4,
    name: "Desktop PC HP Pavilion Gaming TG01-2170m, AMD RYZEN 5 5600G, RAM 16 GB, SSD 512 GB, NVIDIA RTX 3050, WINDOWS 11 HOME",
    price: 1350.0,
    image: "/products/pc2.jpg",
    code: 123459,
    stock: 16,
    new: true,
    utils: {
      type: "PC",
      ram: "16 GB",
      ssd: "512 GB",
      processor: "AMD RYZEN 5 5600G",
      graphics: "NVIDIA RTX 3050",
      os: "WINDOWS 11 HOME",
      color: "BLACK",
      weight: "7.8 kg",
      dimensions: "160 x 360 x 380 mm",
    },
  },
  {
    id: 5,
    name: 'Smartphone Samsung Galaxy S23, 8GB RAM, 256GB Storage, 6.1" AMOLED, ANDROID 13, PHANTOM PINK',
    price: 999.0,
    image: "/products/phone.jpg",
    code: 123460,
    stock: 50,
    new: false,
    utils: {
      type: "Phone",
      ram: "8 GB",
      storage: "256 GB",
      processor: "SNAPDRAGON 8 GEN 2",
      screen: '6.1" AMOLED',
      resolution: "2340x1080",
      os: "ANDROID 13",
      color: "PHANTOM PINK",
      weight: "168 g",
      battery: "3900 mAh",
    },
  },
  {
    id: 6,
    name: 'Smartphone Apple iPhone 14, 6GB RAM, 128GB Storage, 6.1" OLED, IOS 16, MIDNIGHT',
    price: 1199.0,
    discount: 20,
    image: "/products/phone2.jpg",
    code: 123461,
    stock: 40,
    new: false,
    utils: {
      type: "Phone",
      ram: "6 GB",
      storage: "128 GB",
      processor: "A15 BIONIC",
      screen: '6.1" OLED',
      resolution: "2532x1170",
      os: "IOS 16",
      color: "MIDNIGHT",
      weight: "172 g",
      battery: "3279 mAh",
    },
  },
  {
    id: 7,
    name: "Printer HP LaserJet Pro M404dw, MONO LASER, WIFI, USB, A4",
    price: 299.0,
    discount: 20,
    image: "/products/printer.jpg",
    code: 123462,
    stock: 25,
    new: true,
    utils: {
      type: "Printer",
      connectivity: "WIFI, USB",
      color: "BLACK",
      paperSize: "A4",
      weight: "8.5 kg",
      dimensions: "380 x 360 x 250 mm",
    },
  },
  {
    id: 8,
    name: 'Monitor Dell UltraSharp U2723QE 27", 4K UHD, IPS, HDMI/DP, BLACK',
    price: 499.0,
    image: "/products/monitor.jpg",
    code: 123463,
    stock: 18,
    new: true,
    utils: {
      type: "Monitor",
      screen: '27"',
      resolution: "3840x2160",
      panel: "IPS",
      connectivity: "HDMI, DP, USB-C",
      color: "BLACK",
      weight: "6.5 kg",
      dimensions: "613 x 366 x 54 mm",
    },
  },
  {
    id: 9,
    name: "Keyboard Logitech MX Keys, WIRELESS, BLUETOOTH, BLACK",
    price: 129.0,
    image: "/products/keyboard.jpg",
    code: 123464,
    stock: 60,
    new: true,
    utils: {
      type: "Keyboard",
      connectivity: "WIRELESS, BLUETOOTH",
      color: "BLACK",
      weight: "810 g",
      dimensions: "430 x 131 x 20 mm",
    },
  },
];

export const gamingProducts = [
  {
    id: 10,
    name: "Gaming Chair MSI MAG CH130 X, ERGONOMIC DESIGN, BLACK/RED",
    price: 289.0,
    discount: 16,
    image: "/products/chair.jpg",
    code: 223465,
    stock: 20,
    new: true,
    utils: {
      type: "Gaming Chair",
      material: "PU Leather",
      color: "BLACK/RED",
      weight: "21 kg",
      dimensions: "700 x 690 x 1400 mm",
      features: "Ergonomic design, Adjustable armrests, Recline 165°",
    },
  },
  {
    id: 11,
    name: "Gaming Mouse Razer DeathAdder V3 Pro, WIRELESS, 30K DPI, BLACK",
    price: 149.0,
    discount: 10,
    image: "/products/mouse.jpg",
    code: 223466,
    stock: 45,
    new: false,
    utils: {
      type: "Mouse",
      connectivity: "Wireless + USB-C",
      dpi: "30,000",
      color: "BLACK",
      weight: "63 g",
      features: "Ultra-lightweight, Optical switches, 90h battery",
    },
  },
  {
    id: 12,
    name: "Gaming Headset HyperX Cloud Alpha Wireless, 300H Battery, BLACK/RED",
    price: 199.0,
    image: "/products/headset.jpg",
    code: 223467,
    stock: 35,
    new: true,
    utils: {
      type: "Headset",
      connectivity: "Wireless + 3.5mm",
      color: "BLACK/RED",
      battery: "300h",
      weight: "335 g",
      features: "Dual Chamber Drivers, Detachable mic, DTS:X Spatial Audio",
    },
  },
  {
    id: 13,
    name: "Gaming Monitor ASUS ROG Strix XG27AQ, 27\", QHD, 170Hz, IPS",
    price: 549.0,
    image: "/products/gaming-monitor.jpg",
    code: 223468,
    stock: 22,
    new: false,
    utils: {
      type: "Monitor",
      screen: '27"',
      resolution: "2560x1440",
      refreshRate: "170Hz",
      panel: "IPS",
      responseTime: "1ms",
      features: "G-Sync Compatible, HDR400",
      color: "BLACK",
    },
  },
  {
    id: 14,
    name: "Gaming Desk Arozzi Arena, ULTRA-WIDE, 160cm, BLACK",
    price: 399.0,
    image: "/products/gaming-desk.jpg",
    code: 223469,
    stock: 16,
    new: true,
    utils: {
      type: "Desk",
      material: "Steel + MDF",
      color: "BLACK",
      dimensions: "1600 x 820 x 710 mm",
      features: "Full-surface mousepad, Cable management, Adjustable height",
    },
  },
  {
    id: 15,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 16,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 17,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 18,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 19,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 20,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 21,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 22,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
];
