export const newProducts = [
  {
    id: 10,
    name: "Gaming Chair MSI MAG CH130 X, ERGONOMIC DESIGN, BLACK/RED",
    price: 289.0,
    discount: 16,
    image: "/products/chair.jpg",
    code: 223465,
    stock: 20,
    new: true,
    utils: {
      type: "Gaming Chair",
      material: "PU Leather",
      color: "BLACK/RED",
      weight: "21 kg",
      dimensions: "700 x 690 x 1400 mm",
      features: "Ergonomic design, Adjustable armrests, Recline 165°",
    },
  },
  {
    id: 11,
    name: "Gaming Mouse Razer DeathAdder V3 Pro, WIRELESS, 30K DPI, BLACK",
    price: 149.0,
    discount: 10,
    image: "/products/mouse.jpg",
    code: 223466,
    stock: 45,
    new: true,
    utils: {
      type: "Mouse",
      connectivity: "Wireless + USB-C",
      dpi: "30,000",
      color: "BLACK",
      weight: "63 g",
      features: "Ultra-lightweight, Optical switches, 90h battery",
    },
  },
  {
    id: 12,
    name: "Gaming Headset HyperX Cloud Alpha Wireless, 300H Battery, BLACK/RED",
    price: 199.0,
    image: "/products/headset.jpg",
    code: 223467,
    stock: 35,
    new: true,
    utils: {
      type: "Headset",
      connectivity: "Wireless + 3.5mm",
      color: "BLACK/RED",
      battery: "300h",
      weight: "335 g",
      features: "Dual Chamber Drivers, Detachable mic, DTS:X Spatial Audio",
    },
  },
  {
    id: 13,
    name: "Gaming Monitor ASUS ROG Strix XG27AQ, 27\", QHD, 170Hz, IPS",
    price: 549.0,
    image: "/products/gaming-monitor.jpg",
    code: 223468,
    stock: 22,
    new: true,
    utils: {
      type: "Monitor",
      screen: '27"',
      resolution: "2560x1440",
      refreshRate: "170Hz",
      panel: "IPS",
      responseTime: "1ms",
      features: "G-Sync Compatible, HDR400",
      color: "BLACK",
    },
  },
  {
    id: 14,
    name: "Gaming Desk Arozzi Arena, ULTRA-WIDE, 160cm, BLACK",
    price: 399.0,
    image: "/products/gaming-desk.jpg",
    code: 223469,
    stock: 16,
    new: true,
    utils: {
      type: "Desk",
      material: "Steel + MDF",
      color: "BLACK",
      dimensions: "1600 x 820 x 710 mm",
      features: "Full-surface mousepad, Cable management, Adjustable height",
    },
  },
  {
    id: 15,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 16,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 17,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 18,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 19,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 20,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 21,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 22,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
];
export const promoProducts = [
  {
    id: 10,
    name: "Gaming Chair MSI MAG CH130 X, ERGONOMIC DESIGN, BLACK/RED",
    price: 289.0,
    discount: 16,
    image: "/products/chair.jpg",
    code: 223465,
    stock: 20,
    new: false,
    utils: {
      type: "Gaming Chair",
      material: "PU Leather",
      color: "BLACK/RED",
      weight: "21 kg",
      dimensions: "700 x 690 x 1400 mm",
      features: "Ergonomic design, Adjustable armrests, Recline 165°",
    },
  },
  {
    id: 11,
    name: "Gaming Mouse Razer DeathAdder V3 Pro, WIRELESS, 30K DPI, BLACK",
    price: 149.0,
    discount: 10,
    image: "/products/mouse.jpg",
    code: 223466,
    stock: 45,
    new: false,
    utils: {
      type: "Mouse",
      connectivity: "Wireless + USB-C",
      dpi: "30,000",
      color: "BLACK",
      weight: "63 g",
      features: "Ultra-lightweight, Optical switches, 90h battery",
    },
  },
  {
    id: 12,
    name: "Gaming Headset HyperX Cloud Alpha Wireless, 300H Battery, BLACK/RED",
    price: 199.0,
    image: "/products/headset.jpg",
    code: 223467,
    discount: 30,
    stock: 35,
    new: true,
    utils: {
      type: "Headset",
      connectivity: "Wireless + 3.5mm",
      color: "BLACK/RED",
      battery: "300h",
      weight: "335 g",
      features: "Dual Chamber Drivers, Detachable mic, DTS:X Spatial Audio",
    },
  },
  {
    id: 13,
    name: "Gaming Monitor ASUS ROG Strix XG27AQ, 27\", QHD, 170Hz, IPS",
    price: 549.0,
    discount: 30,
    image: "/products/gaming-monitor.jpg",
    code: 223468,
    stock: 22,
    new: false,
    utils: {
      type: "Monitor",
      screen: '27"',
      resolution: "2560x1440",
      refreshRate: "170Hz",
      panel: "IPS",
      responseTime: "1ms",
      features: "G-Sync Compatible, HDR400",
      color: "BLACK",
    },
  },
  {
    id: 14,
    name: "Gaming Desk Arozzi Arena, ULTRA-WIDE, 160cm, BLACK",
    price: 399.0,
    discount: 30,
    image: "/products/gaming-desk.jpg",
    code: 223469,
    stock: 16,
    new: false,
    utils: {
      type: "Desk",
      material: "Steel + MDF",
      color: "BLACK",
      dimensions: "1600 x 820 x 710 mm",
      features: "Full-surface mousepad, Cable management, Adjustable height",
    },
  },
  {
    id: 15,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    discount: 30,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 16,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    discount: 30,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 17,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    discount: 30,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 18,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    discount: 30,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: false,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 19,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    discount: 30,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: false,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 20,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    discount: 30,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 21,
    discount: 30,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: true,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
  {
    id: 22,
    discount: 30,
    name: "RGB Gaming Mouse Pad SteelSeries QcK Prism XL, RGB LIGHTING, CLOTH",
    price: 79.0,
    image: "/products/mousepad.jpg",
    code: 223470,
    stock: 55,
    new: false,
    utils: {
      type: "Mousepad",
      size: "900 x 300 mm",
      surface: "Cloth",
      color: "BLACK + RGB",
      features: "Two-zone RGB lighting, Non-slip rubber base",
      weight: "1.2 kg",
    },
  },
];
